using BepInEx.Configuration;
using NivalisMods.ModCompanion.Api;

var root = Path.Combine(Path.GetTempPath(), "mod-companion-checks-" + Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(root);
SettingsRegistry.ConfigRoot = root;
var checks = 0;
void Check(bool value, string message) { if (!value) throw new Exception(message); checks++; }
void Reject(Action action, string message)
{
    try { action(); } catch (ArgumentException) { checks++; return; }
    throw new Exception(message);
}
try
{
    var resourceIcon = ModIcon.FromResource(typeof(ModIcon).Assembly, "Checks.Icon.png");
    Check(resourceIcon.Data.Length > 8 && resourceIcon.Data.Take(8).SequenceEqual(new byte[] { 137, 80, 78, 71, 13, 10, 26, 10 }), "Embedded PNG resource failed to load.");
    var bytes = new byte[] { 137, 80, 78, 71 };
    var embedded = ModIcon.FromBytes(bytes);
    bytes[0] = 0;
    Check(embedded.Data[0] == 137, "Icon bytes must be copied, not retained from the caller.");
    Reject(() => ModIcon.FromBytes(Array.Empty<byte>()), "Empty icon accepted.");
    Reject(() => ModIcon.FromResource(typeof(ModIcon).Assembly, "missing.png"), "Missing resource accepted.");
    var embeddedMod = SettingsRegistry.Register("tests.embedded", new ModMetadata("Embedded", "Author", "1", Icon: embedded));
    Check(embeddedMod.Icon == embedded && embeddedMod.IconPath == null, "Embedded icon requires an external path.");
    Reject(() => SettingsRegistry.Register("tests.both", new ModMetadata("Both", "Author", "1", IconPath: "/tmp/icon.png", Icon: embedded)), "Ambiguous icon sources accepted.");
    var validMetadata = new ModMetadata("Metadata test", "Test Author", "1.2.3");
    Reject(() => SettingsRegistry.Register("tests.metadata", validMetadata with { Name = " " }), "Blank name accepted.");
    Reject(() => SettingsRegistry.Register("tests.metadata", validMetadata with { Author = "" }), "Missing author accepted.");
    Reject(() => SettingsRegistry.Register("tests.metadata", validMetadata with { Version = " " }), "Blank version accepted.");
    Reject(() => SettingsRegistry.Register("tests.metadata", validMetadata with { IconPath = "relative.png" }), "Relative image path accepted.");
    var metadataMod = SettingsRegistry.Register("tests.metadata", validMetadata);
    Check(metadataMod.Author == "Test Author" && metadataMod.Version == "1.2.3" && metadataMod.IconPath == null, "Required metadata was not retained or optional icon became mandatory.");
    Check(!File.Exists(metadataMod.ConfigPath), "Metadata alone should not create a config file.");
    var defaultMod = SettingsRegistry.Register("tests.default", new ModMetadata("Test Mod", "Test Author", "1.0"));
    Check(defaultMod.ConfigPath == Path.Combine(root, "TestMod", "TestMod.cfg"), "Default config must live in the mod's own folder.");
    var hud = SettingsRegistry.Register("tests.hud", new ModMetadata("HUD Overhaul", "Test Author", "1.0"));
    Check(hud.ConfigPath == Path.Combine(root, "HUDOverhaul", "HUDOverhaul.cfg"), "HUD default path must use its own folder and filename.");
    var mod = SettingsRegistry.Register("tests.first", new ModMetadata("First", "Test Author", "1.0"), "First/settings.cfg");
    var general = mod.Category("General", "General");
    var toggle = general.Toggle("Enabled", "Enable", true);
    var number = general.Stepper("Count", "Count", 2, 1, 5, requiresRestart: true);
    var slider = general.Slider("Scale", "Scale", 1, 0, 2, .25f);
    var choice = general.Choice("Mode", "Mode", "a", new[] { new Choice<string>("a", "First"), new Choice<string>("b", "Second") });
    var binding = general.KeyBinding("Action", "Action", "<Keyboard>/f10", "<Gamepad>/buttonNorth");
    Check(toggle.Value && number.Value == 2, "Defaults were not loaded.");
    Check(ReferenceEquals(mod.Get<int>("General", "Count"), number), "Typed lookup failed.");
    number.Value = 99;
    Check(number.Value == 5 && number.PendingRestart, "Range/restart validation failed.");
    number.Reset();
    Check(number.Value == 2 && !number.PendingRestart, "Reset did not clear restart state.");
    slider.Value = 1.37f;
    Check(slider.Value == 1.25f, "Slider step quantization failed.");
    slider.Value = float.NaN;
    Check(slider.Value == 1f, "Nonfinite slider value was not normalized.");
    choice.Value = "missing";
    Check(choice.Value == "a", "Missing choice did not fall back to default.");
    var notifications = 0;
    toggle.Changed += _ => throw new InvalidOperationException("Deliberate callback error");
    toggle.Changed += _ => notifications++;
    toggle.Value = false; toggle.Value = false;
    Check(notifications == 1, "Callbacks are not isolated or duplicate notifications occurred.");
    choice.Value = "b";
    binding.Keyboard!.Value = "<Keyboard>/f11";
    Check(!mod.IsDirty && File.Exists(mod.ConfigPath), "A changed value must save immediately without opening the UI or calling Save.");
    Check(mod.Save() && !mod.IsDirty, "Explicit developer Save failed.");
    var disk = new ConfigFile(mod.ConfigPath, false) { SaveOnConfigSet = false };
    Check(!disk.Bind("General", "Enabled", true).Value && disk.Bind("General", "Mode", "a").Value == "b", "Saved values did not round-trip.");
    Check(disk.Bind("General", "Action.Keyboard", "").Value == "<Keyboard>/f11", "Binding did not persist.");
    File.WriteAllText(mod.ConfigPath, "[General]\nEnabled = true\nCount = 100\nMode = invalid\nScale = 1.61\nAction.Keyboard = <Keyboard>/f12\n");
    mod.Reload();
    Check(toggle.Value && notifications == 2 && number.Value == 5 && choice.Value == "a" && slider.Value == 1.5f, "Reload validation/notification failed.");
    Reject(() => SettingsRegistry.Register("tests.first", new ModMetadata("Duplicate", "Test Author", "1.0")), "Duplicate ID allowed.");
    Reject(() => SettingsRegistry.Register("tests.second", new ModMetadata("Other", "Test Author", "1.0"), "First/settings.cfg"), "Two owners allowed for one path.");
    Reject(() => SettingsRegistry.Register("tests.escape", new ModMetadata("Escape", "Test Author", "1.0"), "../outside.cfg"), "Path traversal allowed.");
    Reject(() => general.Toggle("Enabled", "Duplicate", true), "Duplicate key allowed.");
    Reject(() => mod.Category("General", "Duplicate"), "Duplicate category allowed.");
    var existingFile = new ConfigFile(Path.Combine(root, "existing.cfg"), false) { SaveOnConfigSet = true };
    var existingEntry = existingFile.Bind("Features", "Active", true);
    var other = SettingsRegistry.Register("tests.existing", new ModMetadata("Existing", "Test Author", "1.0"), existingFile);
    var exposed = other.Category("Features", "Features").BindToggle("Active", "Active", existingEntry);
    exposed.Value = false;
    Check(!existingEntry.Value && existingFile.SaveOnConfigSet, "Existing config ownership/value was changed.");
    existingEntry.Value = true;
    Check(exposed.Value, "Changes to original entry do not reach wrapper.");
    Reject(() => general.BindToggle("WrongFile", "Wrong", existingEntry), "Cross-file entry was accepted.");
    var sections = SettingsRegistry.Register("tests.sections", new ModMetadata("Sections", "Test Author", "2.0", "Description", "/tmp/example-icon.png"));
    _ = sections.Controls; _ = sections.Developer; _ = sections.Info;
    sections.AddCategory("Empty", "Empty category");
    Check(sections.Sections.Count == 0, "Empty sections must stay hidden, even after API access.");
    sections.Controls.AddParagraph("Help", "Select an action to rebind it.");
    Check(sections.Sections.Count == 0, "Controls help alone must not create a bindings tab.");
    Check(sections.IconPath == "/tmp/example-icon.png" && sections.Author == "Test Author" && sections.Version == "2.0" && sections.Description == "Description" && sections.Sections.Count == 0, "Metadata must not create an Info tab.");
    sections.Info.AddHeading("About");
    sections.Info.AddParagraph("First paragraph.");
    Check(sections.Sections.Single().Kind == SectionKind.Info && sections.Info.Blocks.Select(b => b.Kind).SequenceEqual(new[] { InfoBlockKind.Heading, InfoBlockKind.Paragraph }), "Info blocks or visibility are incorrect.");
    var verbose = sections.Developer.AddVerboseLogging();
    verbose.Hint = "Additional diagnostic messages.";
    Check(verbose.Hint == "Additional diagnostic messages.", "Per-setting hint was not retained.");
    var input = sections.Controls.AddInput("Inspect", "Inspect", "<Keyboard>/f8", "<Gamepad>/buttonSouth");
    var native = sections.Controls.AddNativeInput("Inventory", "Inventory", "Inventory");
    var custom = sections.AddCategory("Farm", "Farm");
    custom.Toggle("Enabled", "Enable", true);
    custom.KeyBinding("LocalAction", "Local action", "<Keyboard>/f9");
    Check(!SettingsRegistry.DeveloperMode && sections.Sections.All(x => x.Kind != SectionKind.Developer), "Developer settings must be hidden by default.");
    sections.Developer.Settings.Button("TestAction", "Run developer test", () => { });
    sections.Developer.Settings.Toggle("TestFeature", "Enable test feature", false);
    SettingsRegistry.DeveloperMode = true;
    Check(sections.Sections.Single(x => x.Kind == SectionKind.Developer).Category!.Entries.Count == 3, "Developer category must accept normal controls and actions.");
    SettingsRegistry.DeveloperMode = false;
    Check(sections.Sections.All(x => x.Kind != SectionKind.Developer), "Developer tab did not disappear.");
    SettingsRegistry.DeveloperMode = true;
    Check(sections.Sections.Select(x => x.Key).SequenceEqual(new[] { "Farm", "Controls", "Developer", "Info" }), "Custom and standard tab order is incorrect.");
    Check(custom.Entries.OfType<KeyBindingSetting>().Count() == 1 && sections.Sections.Single(x => x.Kind == SectionKind.Controls).Category!.Entries.Count == 3, "Custom bindings must stay in their category.");
    Check(native.NativeAction == "Inventory" && native.Keyboard == null, "Native input adapter changed ownership.");
    Check(!verbose.Value && ReferenceEquals(sections.Get<bool>("Developer", "Verbose"), verbose), "Verbose logging handle is not accessible through typed lookup.");
    verbose.Value = true; input.Keyboard!.Value = "<Keyboard>/f7"; input.Gamepad!.Value = "<Gamepad>/buttonNorth";
    Check(sections.Save(), "Standard settings did not save.");
    var savedSections = new ConfigFile(sections.ConfigPath, false);
    Check(savedSections.Bind("Developer", "Verbose", false).Value && savedSections.Bind("Controls", "Inspect.Gamepad", "").Value == "<Gamepad>/buttonNorth", "Logging/controller settings did not round-trip.");
    Check(!File.ReadAllText(sections.ConfigPath).Contains("First paragraph."), "Info presentation must not be persisted as configuration.");
    var savedText = File.ReadAllText(sections.ConfigPath);
    verbose.Value = false; input.Gamepad.Value = "";
    var immediateDisk = new ConfigFile(sections.ConfigPath, false);
    Check(!immediateDisk.Bind("Developer", "Verbose", true).Value && immediateDisk.Bind("Controls", "Inspect.Gamepad", "missing").Value == "", "Changes did not save synchronously.");
    File.WriteAllText(sections.ConfigPath, savedText);
    sections.Reload();
    Check(verbose.Value && input.Gamepad.Value == "<Gamepad>/buttonNorth", "Standard settings reload failed.");
    sections.ResetDefaults();
    Check(!verbose.Value && input.Keyboard.Value == "<Keyboard>/f8" && input.Gamepad.Value == "<Gamepad>/buttonSouth", "Standard settings reset failed.");
    Check(sections.Info.Blocks.Count == 2, "Reset must preserve Info content.");
    Reject(() => sections.AddCategory("controls", "Custom"), "Reserved standard category key was accepted.");
    Reject(() => sections.Developer.AddVerboseLogging(), "Duplicate logging preference accepted.");
    Reject(() => sections.Controls.AddInput("Inspect", "Duplicate"), "Duplicate control accepted.");
    Reject(() => sections.Info.AddParagraph(" "), "Empty info block accepted.");
    var failing = SettingsRegistry.Register("tests.fail", new ModMetadata("Failure", "Test Author", "1.0"), "Failure/settings.cfg");
    failing.Category("Test", "Test").Toggle("Value", "Value", true);
    File.Delete(failing.ConfigPath);
    Directory.CreateDirectory(failing.ConfigPath);
    failing.Get<bool>("Test", "Value").Value = false;
    Check(!failing.Save() && failing.IsDirty && failing.SaveError != null, "Save failure lost dirty state.");
    Directory.Delete(failing.ConfigPath);
    Check(failing.Save() && failing.SaveError == null, "Save did not recover after failure.");
    Console.WriteLine($"PASS: {checks} configuration checks.");
}
finally { Directory.Delete(root, true); }
